#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Luiz Lopes — Senior DevOps Engineer
url: 'https://luizlopes.io'
baseurl: '' #change it according to your repository name
description: Résumé of Luiz Lopes, a Software Development professional based in Missoula, MT.

# Metadata
site_name: luizlopes.io
locale: en_US
image: /assets/images/profile.jpeg
first_name: Luiz
last_name: Lopes
username: theprivileges

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: '#358699' #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false

# Jekyll

plugins:
  - github-pages
