version: '3'
services:
  jekyll_serve:
    image: jekyll/jekyll:3
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - LL_ALL=en_US.UTF-8
      - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      - RUBY_VERSION=2.7.3
    volumes:
      - '.:/srv/jekyll'
    ports:
      - 4000:4000
    command: 'jekyll serve -l'
